/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Service.CaixaService;
import controller.Compra.ControllerAbrirCaixa;
import controller.Compra.ControllerPontoDeVenda;
import controller.cadastro.ControllerCadastroEndereco;
import controller.cadastro.ControllerCadastroBairro;
import view.Cadastro.CadastroEnderecoView;
import view.Cadastro.CadastroProdutoView;
import view.Cadastro.CadastroBairrosView;
import view.Cadastro.CadastroCidadesView;
import controller.cadastro.ControllerCadastroCidade;
import controller.cadastro.ControllerCadastroProduto;
import view.Cadastro.CadastroCarteirinhaView;
import controller.cadastro.ControllerCadastroCarteirinha;
import controller.cadastro.ControllerCadastroCliente;
import controller.cadastro.ControllerCadastroFornecedor;
import controller.cadastro.ControllerCadastroFuncionario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JMenuItem;
import model.bo.Caixa;
import view.Busca.VendaView;
import view.Cadastro.CadastroClienteView;
import view.Cadastro.CadastroFornecedorView;
import view.Cadastro.CadastroFuncionarioView;
import view.Compra.AbreCaixaView;
import view.Compra.PontoDeVendaView;

/**
 *
 * @author aluno
 */
public class MenuPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipalView
     */
    public MenuPrincipalView() {

        setExtendedState(NORMAL);
        initComponents();
        //DAO.Persiste.getInstance();
    }

    public JMenuItem getjMenuItemSair() {
        return jMenuItemSair;
    }

    public void setjMenuItemSair(JMenuItem jMenuItemSair) {
        this.jMenuItemSair = jMenuItemSair;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemFornecedor = new javax.swing.JMenuItem();
        jMenuItemFuncionario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBairro = new javax.swing.JMenuItem();
        jMenuItemCidade = new javax.swing.JMenuItem();
        jMenuItemEndereco = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCarterinha = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuMovimentos = new javax.swing.JMenu();
        PontoDeVenda = new javax.swing.JMenuItem();
        jMenuContas = new javax.swing.JMenu();
        jMenuItemAPagar = new javax.swing.JMenuItem();
        jMenuItemAVencer = new javax.swing.JMenuItem();
        jMenuItemAReceber = new javax.swing.JMenuItem();
        jMenuItemForaDeCaixa = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(923, 627));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/restaurante.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 102, 0));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(252, 30));

        jMenuCadastros.setText("Cadastros");

        jMenuItemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Blue pin.png"))); // NOI18N
        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.setPreferredSize(new java.awt.Dimension(114, 22));
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCliente);

        jMenuItemFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Green pin.png"))); // NOI18N
        jMenuItemFornecedor.setText("Fornecedor");
        jMenuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedorActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFornecedor);

        jMenuItemFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItemFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Black pin.png"))); // NOI18N
        jMenuItemFuncionario.setText("Funcionario");
        jMenuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFuncionarioActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemFuncionario);
        jMenuCadastros.add(jSeparator1);

        jMenuItemBairro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemBairro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Blue pin.png"))); // NOI18N
        jMenuItemBairro.setText("Bairro");
        jMenuItemBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBairroActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemBairro);

        jMenuItemCidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Green pin.png"))); // NOI18N
        jMenuItemCidade.setText("Cidade");
        jMenuItemCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCidadeActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCidade);

        jMenuItemEndereco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItemEndereco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Home.png"))); // NOI18N
        jMenuItemEndereco.setText("Endereço");
        jMenuItemEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnderecoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemEndereco);
        jMenuCadastros.add(jSeparator2);

        jMenuItemCarterinha.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItemCarterinha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Briefcase.png"))); // NOI18N
        jMenuItemCarterinha.setText("Carterinha");
        jMenuItemCarterinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCarterinhaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCarterinha);
        jMenuCadastros.add(jSeparator3);

        jMenuItemProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItemProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Buy.png"))); // NOI18N
        jMenuItemProduto.setText("Produto");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemProduto);
        jMenuCadastros.add(jSeparator4);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Exit.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemSair);

        jMenuBar1.add(jMenuCadastros);

        jMenuMovimentos.setText("Movimentos");

        PontoDeVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        PontoDeVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Buy.png"))); // NOI18N
        PontoDeVenda.setText("Abrir Caixa");
        PontoDeVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PontoDeVendaActionPerformed(evt);
            }
        });
        jMenuMovimentos.add(PontoDeVenda);

        jMenuContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Clipboard.png"))); // NOI18N
        jMenuContas.setText("Contas");

        jMenuItemAPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Blue bookmark.png"))); // NOI18N
        jMenuItemAPagar.setText("A Pagar");
        jMenuItemAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAPagarActionPerformed(evt);
            }
        });
        jMenuContas.add(jMenuItemAPagar);

        jMenuItemAVencer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Bookmark.png"))); // NOI18N
        jMenuItemAVencer.setText("A Vencer");
        jMenuContas.add(jMenuItemAVencer);

        jMenuItemAReceber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Green bookmark.png"))); // NOI18N
        jMenuItemAReceber.setText("A Receber");
        jMenuContas.add(jMenuItemAReceber);

        jMenuItemForaDeCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Black bookmark.png"))); // NOI18N
        jMenuItemForaDeCaixa.setText("Fora de Caixa");
        jMenuContas.add(jMenuItemForaDeCaixa);

        jMenuMovimentos.add(jMenuContas);

        jMenuBar1.add(jMenuMovimentos);

        jMenuRelatorios.setText("Relatorios");
        jMenuBar1.add(jMenuRelatorios);

        jMenuAjuda.setText("Ajuda");
        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBairroActionPerformed
        CadastroBairrosView cadastroBairrosView = new CadastroBairrosView(null, true);
        ControllerCadastroBairro controllerCadastroBairro = new ControllerCadastroBairro(cadastroBairrosView);
        cadastroBairrosView.setVisible(true);
    }//GEN-LAST:event_jMenuItemBairroActionPerformed

    private void jMenuItemAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAPagarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAPagarActionPerformed

    private void jMenuItemEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnderecoActionPerformed
        CadastroEnderecoView cadastroEnderecoView = new CadastroEnderecoView(null, true);
        ControllerCadastroEndereco controllerCadastroEndereco = new ControllerCadastroEndereco(cadastroEnderecoView);
        cadastroEnderecoView.setVisible(true);
    }//GEN-LAST:event_jMenuItemEnderecoActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        CadastroProdutoView cadastroProdutoView = new CadastroProdutoView(null, true);
        ControllerCadastroProduto cadastroProduto = new ControllerCadastroProduto(cadastroProdutoView);
        cadastroProdutoView.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jMenuItemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCidadeActionPerformed
        CadastroCidadesView cadastroCidadesView = new CadastroCidadesView(null, true);
        ControllerCadastroCidade controllerCadastroCidade = new ControllerCadastroCidade(cadastroCidadesView);
        cadastroCidadesView.setVisible(true);
    }//GEN-LAST:event_jMenuItemCidadeActionPerformed

    private void jMenuItemCarterinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCarterinhaActionPerformed
        CadastroCarteirinhaView cadastroCarteirinhaView = new CadastroCarteirinhaView(null, true);
        ControllerCadastroCarteirinha controllerCadastroCarteirinha = new ControllerCadastroCarteirinha(cadastroCarteirinhaView);
        cadastroCarteirinhaView.setVisible(true);
    }//GEN-LAST:event_jMenuItemCarterinhaActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        this.dispose();

    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
       CadastroClienteView cadastroClienteView = new CadastroClienteView(null, true);
       ControllerCadastroCliente controllerCadastroCliente = new ControllerCadastroCliente(cadastroClienteView);
       cadastroClienteView.setVisible(true);
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedorActionPerformed
        CadastroFornecedorView cadastroFornecedorView = new CadastroFornecedorView(null, true);
        ControllerCadastroFornecedor contollerCadastroFornecedor = new ControllerCadastroFornecedor(cadastroFornecedorView);
        cadastroFornecedorView.setVisible(true);
    }//GEN-LAST:event_jMenuItemFornecedorActionPerformed

    private void jMenuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFuncionarioActionPerformed
        CadastroFuncionarioView cadastroFuncionarioView = new CadastroFuncionarioView(null, true);
        ControllerCadastroFuncionario controllerCadastroFuncionario = new ControllerCadastroFuncionario(cadastroFuncionarioView);
        cadastroFuncionarioView.setVisible(true);
    }//GEN-LAST:event_jMenuItemFuncionarioActionPerformed

    private void PontoDeVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PontoDeVendaActionPerformed
        
        List<Caixa> lista = new ArrayList();
        lista = CaixaService.carregar();
        if(!lista.isEmpty()){
            if(lista.size() == 1 && lista.get(0).getStatus() == 'F'){
                AbreCaixaView abreCaixaView = new AbreCaixaView(null, true);
                ControllerAbrirCaixa controllerAbrirCaixa = new ControllerAbrirCaixa(abreCaixaView);
                abreCaixaView.setVisible(true);
            }else if(lista.get(lista.size() - 1).getStatus() == 'F'){
                AbreCaixaView abreCaixaView = new AbreCaixaView(null, true);
                ControllerAbrirCaixa controllerAbrirCaixa = new ControllerAbrirCaixa(abreCaixaView);
                abreCaixaView.setVisible(true);
            }else{
                PontoDeVendaView pontoDeVendaView = new PontoDeVendaView(null, true);
                ControllerPontoDeVenda controllerPontoDeVenda = new ControllerPontoDeVenda(pontoDeVendaView);
                pontoDeVendaView.getIdFuncionario().setText(lista.get(lista.size() - 1).getFuncionario().getId()+"");
                pontoDeVendaView.setVisible(true);
            }
        }else{
            AbreCaixaView abreCaixaView = new AbreCaixaView(null, true);
            ControllerAbrirCaixa controllerAbrirCaixa = new ControllerAbrirCaixa(abreCaixaView);
            abreCaixaView.setVisible(true);
        }
    }//GEN-LAST:event_PontoDeVendaActionPerformed


    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem PontoDeVenda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuContas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAPagar;
    private javax.swing.JMenuItem jMenuItemAReceber;
    private javax.swing.JMenuItem jMenuItemAVencer;
    private javax.swing.JMenuItem jMenuItemBairro;
    private javax.swing.JMenuItem jMenuItemCarterinha;
    private javax.swing.JMenuItem jMenuItemCidade;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemEndereco;
    private javax.swing.JMenuItem jMenuItemForaDeCaixa;
    private javax.swing.JMenuItem jMenuItemFornecedor;
    private javax.swing.JMenuItem jMenuItemFuncionario;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuMovimentos;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
